mock: 
	mockery --dir=. --name=Builder --filename=clue.go --output=mocks --outpkg=mocks
	mockery --dir=. --name=Meta --filename=meta.go --output=mocks --outpkg=mocks
	mockery --dir=. --name=Sender --filename=sender.go --output=mocks --outpkg=mocks
