package snap

const X_TIMESTAMP = "X-TIMESTAMP"
const X_SIGNATURE = "X-SIGNATURE"
const X_CLIENT_KEY = "X-CLIENT-KEY"
const X_PARTNER_ID = "X-PARTNER-ID"
const X_EXTERNAL_ID = "X-EXTERNAL-ID"
const X_IP_ADDRESS = "X-IP-ADDRESS"
const X_DEVICE_ID = "X-DEVICE-ID"
const X_LONGITUDE = "X-LONGITUDE"
const X_LATITUDE = "X-LATITUDE"
const X_IDEMPOTENTCY = "X-Idempotency-Key"
